version: "3"

services:
  
  ingestor:

    build: ./mysql_ingestor/

    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${HEIMDALL}:mysql-ingestor-${IMAGE_TAG}
    container_name: mysql_ingestor
    ports: 
      - "8000:8000"
    networks:
      - tower


  influx:

    build: ./influxdb_ingestor

    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${HEIMDALL}:influxdb-ingestor-${IMAGE_TAG}
    container_name: influx_container
    ports:
      - "9000:9000"
    networks:
      - tower

  mqtt:
  
    build: ./mqtt/
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${HEIMDALL}:mqtt-${IMAGE_TAG}
    #entrypoint: ["/bin/sh", "-c", "sleep 600" ]
    container_name: mqtt
    ports:
      - "3333:3333"
    networks:
      - tower


  etl:
    build: ./jarvis/
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${HEIMDALL}:etl-${IMAGE_TAG}
    container_name: etl
    ports:
      - "6000:6000"
    networks:
      - tower

  heimdall:
     
    build: ./heimdall
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${HEIMDALL}:heimdall-${IMAGE_TAG}
    container_name: heimdall
    ports:
      - "7000:7000"
    networks:
      - tower
  
        #  patrol:
        # build: ~/dockerize/TowerWatch/patrol
        # image: patrol:latest
        # container_name: patrol
        # ports:
        # - "6999:6999"
        # networks:
        # - tower

networks:
  tower:
  name: backend_tower
    driver: bridge
